### ISSUE TITLE
I am unable to get FUSD on testnet

### ISSUE THREAD

**Issue by oldhand7** [nporium-labs/npm-cadence-contract#8]
I am unable to get FUSD on testnet because it says my accounts don't have FUSD enabled, even after I did the steps outlined.

**Comment by kurmogs** [comment]
I've created a thread for your message. Please continue any relevant discussion in this thread. 

 You can rename this thread using /title <new title>

**Comment by kurmogs** [comment]
Have you added the fusd wallet in your storage? Ok blocto or test-find.xyz?

**Comment by oldhand7** [comment]
I thought I did on blocto
how do I do it on testnet for blocto?
I did the wallet instructions on mobile
but I am not sure if thats mainnet
